#!/usr/bin/env node

import { program } from "commander";
import fs from "fs";
import path from "path";
import os from "os";

// --- 0. Configuration and constant definitions ---

// Use PALS_HOME environment variable if set; otherwise use a directory under the user's home.
const HOME_DIR = os.homedir();
const BASE_DIR = process.env.PALS_HOME || path.join(HOME_DIR, ".ps-aliases");
const BIN_DIR = path.join(BASE_DIR, "bin");
const CONFIG_FILE = path.join(BASE_DIR, "config.json");

// Common alias templates
const ALIAS_TEMPLATES = {
  ll: "Get-ChildItem -Verbose",
  ls: "Get-ChildItem",
  grep: "Select-String",
  touch: "New-Item -ItemType File",
  cat: "Get-Content",
  which: "Get-Command",
  rm: "Remove-Item",
  cp: "Copy-Item",
  mv: "Move-Item",
};

// Directory initialization function
const initDirectories = () => {
  if (!fs.existsSync(BIN_DIR)) {
    fs.mkdirSync(BIN_DIR, { recursive: true });
  }
};

// Helper: create a .ps1 file
const createAliasScript = (aliasName, commandStr) => {
  const filePath = path.join(BIN_DIR, `${aliasName}.ps1`);
  const scriptContent = `
# Generated by pals
${commandStr} @args
`;
  fs.writeFileSync(filePath, scriptContent);
  return filePath;
};

// Run initialization
initDirectories();

// CLI setup
program
  .name("pals")
  .description("PowerShell Alias Manager (Advanced)")
  .version("0.1.0");

// --- 1. Create: Add an alias ---
program
  .command("add <aliasName> <command...>")
  .description("Create a new alias (e.g., pals add touch New-Item)")
  .action((aliasName, commandParts) => {
    try {
      const targetCommand = commandParts.join(" ");
      const filePath = createAliasScript(aliasName, targetCommand);

      console.log(
        `✅ Alias added successfully: ${aliasName} -> "${targetCommand}"`,
      );
      console.log(`   File path: ${filePath}`);
    } catch (err) {
      console.error("❌ Error:", err.message);
    }
  });

// --- 2. Delete: Remove an alias ---
program
  .command("remove <aliasName>")
  .alias("rm")
  .description("Remove an alias")
  .action((aliasName) => {
    try {
      const filePath = path.join(BIN_DIR, `${aliasName}.ps1`);

      if (!fs.existsSync(filePath)) {
        console.error(`⚠️  Alias not found: "${aliasName}"`);
        return;
      }

      fs.unlinkSync(filePath);
      console.log(`🗑️  Alias removed successfully: ${aliasName}`);
    } catch (err) {
      console.error("❌ Error:", err.message);
    }
  });

// --- 3. List: Display aliases ---
program
  .command("list")
  .alias("ls")
  .description("List aliases")
  .action(() => {
    try {
      const files = fs
        .readdirSync(BIN_DIR)
        .filter((file) => file.endsWith(".ps1"));

      if (files.length === 0) {
        console.log("No aliases yet.");
        return;
      }

      console.log(`📂 Saved in: ${BIN_DIR}`);
      console.log("-------------------------------------------");
      console.log(`${"ALIAS".padEnd(12)} | COMMAND`);
      console.log("-------------------------------------------");

      files.forEach((file) => {
        const aliasName = file.replace(".ps1", "");
        const content = fs.readFileSync(path.join(BIN_DIR, file), "utf-8");
        // Extract the command part
        const lines = content
          .split("\n")
          .filter((line) => line.trim() !== "" && !line.startsWith("#"));
        const command = lines[0]?.replace(" @args", "").trim() || "Unknown";

        console.log(`${aliasName.padEnd(12)} | ${command}`);
      });
      console.log("-------------------------------------------");
    } catch (err) {
      console.error("❌ Error:", err.message);
    }
  });

// --- 4. Templates: Template utilities ---
const templateCommand = program
  .command("template")
  .description("Template utilities");

templateCommand
  .command("list")
  .description("List available templates")
  .action(() => {
    console.log("📋 Available templates:");
    Object.entries(ALIAS_TEMPLATES).forEach(([key, val]) => {
      console.log(`  - ${key.padEnd(8)} -> ${val}`);
    });
    console.log('\nTo apply: pals template apply <name> (or "all")');
  });

templateCommand
  .command("apply <name>")
  .description('Create aliases by applying a template (or "all" to apply all)')
  .action((name) => {
    try {
      if (name === "all") {
        let count = 0;
        Object.entries(ALIAS_TEMPLATES).forEach(([key, val]) => {
          createAliasScript(key, val);
          count++;
        });
        console.log(`✅ ${count} templates applied successfully.`);
      } else {
        const command = ALIAS_TEMPLATES[name];
        if (!command) {
          console.error(
            `❌ Template "${name}" does not exist. Run "pals template list" to check.`,
          );
          return;
        }
        createAliasScript(name, command);
        console.log(
          `✅ Template applied successfully: ${name} -> "${command}"`,
        );
      }
    } catch (err) {
      console.error("❌ Error:", err.message);
    }
  });

// --- 5. Config/Setup: Display settings and paths ---
program
  .command("config")
  .description("Displays the current settings and destination path")
  .action(() => {
    console.log("⚙️  Current settings:");
    console.log(`   PALS_HOME (Root) : ${BASE_DIR}`);
    console.log(`   Bin Directory    : ${BIN_DIR}`);
    console.log(
      `   Config File      : ${CONFIG_FILE} (uses default values if not present)`,
    );
    console.log(
      '\nℹ️  To change the storage location, set the "PALS_HOME" environment variable.',
    );
  });

program
  .command("path")
  .description("Display command to add the directory to PowerShell PATH")
  .action(() => {
    console.log(
      "\nPlease add the following directory to your PowerShell PATH:\n",
    );
    console.log(`  ${BIN_DIR}`);
    console.log("\n--- Example of appending to PowerShell ($PROFILE) ---");
    console.log(`$env:PATH += ";${BIN_DIR}"`);
  });

program.parse(process.argv);
